FROM nginx
MAINTAINER Jinho Kim <kazami20@naver.com>

# Run upgrades
#RUN apt-get update

# Install basic packages
#RUN apt-get -y openssl-devel 

# Install apache2
#RUN apt-get -qq -y install apache2
#ENV APACHE_RUN_USER www-data
#ENV APACHE_RUN_GROUP www-data
#ENV APACHE_LOG_DIR /var/log/apache2
#RUN a2enmod rewrite

#EXPOSE 80
#CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]
